### ISSUE TITLE
Make network roles idempotent

### ISSUE THREAD

**Issue by larsks** [innabox/cloudkit-aap#52]
It should not be an error to delete a network that does not exist. The following playbook:

```
- hosts: localhost
  gather_facts: false
  tasks:
    - include_role:
        name: massopencloud.esi.network
      vars:
        network_suffix: larstest
        network_state: absent
```

Fails with the following error if the given network has already been deleted:

> `TASK [massopencloud.esi.network : Check that exactly one network matching the ident exists]`
> `fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["openstack", "network", "show", "network-larstest", "-f", "json"], "delta": "0:00:02.631396", "end": "2025-05-19 20:57:53.408106", "msg": "non-zero return code", "rc": 1, "start": "2025-05-19 20:57:50.776710", "stderr": "Error while executing command: No Network found for network-larstest", "stderr_lines": ["Error while executing command: No Network found for network-larstest"], "stdout": "", "stdout_lines": []}`
