### ISSUE TITLE
Cluster templates should be roles

### ISSUE THREAD

**Issue by larsks** [innabox/cloudkit-aap#8]
It looks like right a now a "cluster template" is just a variable file, but that's not going to work in the long term -- we need cluster templates to be able to perform arbitrary post-install tasks (like, "install openshift ai" or "configure oauth", etc). A "cluster template" should be a role that then includes other roles in order to get things done. E.g., if I ask for an `ocp_4_17_small` cluster, that should have a tasks file that looks something like:

```
- name: Install the hosted cluster
  include_role:
    name: hosted_cluster
```

Whereas a more complicated template might look like:

```
- name: Install the hosted cluster
  include_role:
    name: hosted_cluster

- name: Install and configure OpenShift AI
  include_role:
    name: install_openshift_ai

- name: Configure github oauth
  include_role:
    name: github_oauth
```
